sudo: required

services:
  - docker

before_install:
 - docker --version
 - docker build -t uniplug/youtrack:alpine-$TRAVIS_COMMIT -f Dockerfile .
 - docker run -d uniplug/youtrack:alpine-$TRAVIS_COMMIT

script:
 - docker ps | grep -q uniplug/youtrack:alpine-$TRAVIS_COMMIT
